stocksapp/xplore/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp, name="signup"),
]

stocksapp/xplore/profilepage/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'profilepage'

urlpatterns = [
    url('profile/', views.CustomerProfile, name="profilepage"),
]

stocksapp/xplore/xplore/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name='home'),
    path('history/',include('history.urls',  namespace='history')),
    path('profile/', include('profilepage.urls',  namespace='profilepage')),
    path('homeapp/', include('homeapp.urls',  namespace='homeapp')),
    path('accounts/', include('accounts.urls',  namespace='accounts')),

]

stocksapp/xplore/templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="base.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:500">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Netflix Sans:500,400">
<script src="https://kit.fontawesome.com/70de31fc4e.js" crossorigin="anonymous"></script>
<script
src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs="
crossorigin="anonymous"></script>
    {% block head_block %}
    {% endblock %}
    <title>Stocks</title>
  </head>
  <body>
    
  <nav class="navbar navbar-expand-lg navbar-light navprops " style="background-color: white;">
  
      <div class="container-fluid justify-content-between container" style="box-shadow: 0px 1px 4px rgba(0, 0, 0, 0.25);border-radius: 5px 5px 5px 5px;padding-left: 20px;padding-right: 10px;padding-top: 6px;padding-bottom: 6px;" >
      <!-- Left elements -->
      <div class="d-flex">
        <!-- Brand -->
        <a class="navbar-brand me-2 mb-1 d-flex align-items-center" style="color: gray;
     
        font-weight: 400;
      letter-spacing: 0px;
      text-align: center;
      color: rgb(86, 86, 86);">Stocks
        </a>
      </div>
      <form class="input-group w-auto my-auto d-none d-sm-flex">
        <div class="searchbarDiv" style="border-radius: 7px;
        margin-left: 30px;
        width: 25em;
        background-color: rgba(128, 128, 128, 0.137);
         /* border: rgba(128, 128, 128, 0.308);
                        border-style: solid;
                        border-width: 0.2px;  */
       ">
        <div class="input-group">
          <div class="input-group-prepend">
          <button id="button-addon2" type="submit" class="btn btn-link text-warning"><i class="fa fa-search"  style="color: grey;margin: 3px 3px;"></i></button>
        </div>
        <input
          autocomplete="off"
          type="search"
          class="form-control border-0"
          placeholder="Search"
          style="min-width: 125px; max-width: 630px; background-color:  rgba(128, 128, 128, 0.041);"
        />
      </div>
    </div>
       </form>


       {% if user.is_authenticated %}
          <a href="{% url 'profilepage:profilepage' %}"> <img src="{% static 'download.png' %}" style="width:40px; height:40px; margin-right:10px;"></img> </a>
        <div class="d-flex">
          <a href="{% url 'accounts:logout' %}" class="btn btn-primary container" style="  background-color: #46c23a;;
            color: white;
          font-family: Roboto;
          font-style: normal;
          text-transform: uppercase;"  >Log Out</a>
        </div>
      {% else %}
            <div class="d-flex">
            <a href="{% url 'accounts:login' %}" class="btn btn-primary container" style="  background-color: #46c23a;;
            color: white;
            font-family: Roboto;
            font-style: normal;
            text-transform: uppercase;"  >Log In / Sign Up</a>
      {% endif %}

    </div>

      </div>

    </div>

  </nav>

  
    {% block body_block %}
    {% endblock %}

    <footer align="center" > All the Trasations made take aproximately 1 minute to process</footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>