stocksapp/xplore/history/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'history'

urlpatterns = [
    url('', views.UserHistory, name="buying_history"),
    #url('sellinghistory/', views.UserHistorySelling, name="selling_history"),
]

stocksapp/xplore/homeapp/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'homeapp'

urlpatterns = [
    url('home/', views.HomePage, name="homepage"),
    # url('stockbuy/', views.StockBuy, name="stockbuy"),
]
    

stocksapp/xplore/xplore/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name='home'),
    path('history/',include('history.urls',  namespace='history')),
    path('profile/', include('profilepage.urls',  namespace='profilepage')),
    path('homeapp/', include('homeapp.urls',  namespace='homeapp')),
    path('accounts/', include('accounts.urls',  namespace='accounts')),

]

stocksapp/xplore/homeapp/models.py
import json
from django.db import models
from django.db.models.fields import CharField, DateTimeField, EmailField, IntegerField, URLField, TextField

from accounts.models import UserProfile
from django.utils import timezone 
# Create your models here.



class Stocktype(models.Model):
    stockId=models.CharField("stockId",max_length=20,unique=True)
    stockName=models.CharField("stockName",max_length=256)
  #  lastPrice=models.IntegerField('lastPrice',default=0)
  #  newPrice=models.IntegerField('newPrice',default=0)
    def __str__(self):
        return str(self.stockId)+ " "+ str(self.stockName)
    

class PriceChange(models.Model):
    price=models.IntegerField('price',default=0)
    is_linked=models.ForeignKey(Stocktype,on_delete=models.CASCADE)
    updatedAt=models.TimeField('updatedAt',default=timezone.now)

    def __str__(self):
        return str(self.is_linked)+str(self.price)+" "+str(self.updatedAt)
    


class OrgStocks(models.Model):
    stockType = models.OneToOneField(Stocktype,on_delete=models.CASCADE)
    stockAmount = models.IntegerField('stockAmount',default=0)

    def __str__(self):
      return  str(self.stockType)+" "+str(self.stockAmount)


"""
class UserStocks(models.Model):
    class StockType(models.TextChoices):
        StockA = 'A', ('StockA')
        StockB = 'B', ('StockB')
        StockC = 'C', ('StockC')
        StockD = 'D', ('StockD')
        StockE = 'E', ('StockE')
        StockF = 'F', ('StockF')
        StockG = 'G', ('StockG')

    stockType = models.CharField(max_length = 1, choices= StockType.choices)
    username = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    stockNumber = IntegerField('stockNumber', default=10000)
    
    def __str__(self):
      return 'StockType'

class StocksRecipts(models.Model):
    class StockType(models.TextChoices):
        StockA = 'A', ('StockA')
        StockB = 'B', ('StockB')
        StockC = 'C', ('StockC')
        StockD = 'D', ('StockD')
        StockE = 'E', ('StockE')
        StockF = 'F', ('StockF')
        StockG = 'G', ('StockG')

    TagChoices  = (
        ( 'Buy', 'Buy'),
        ('Sell', 'Sell'),
    )

    stockType = models.CharField(max_length = 1, choices= StockType.choices)
    seller = models.ForeignKey(UserStocks, on_delete=models.CASCADE, related_name= 'seller_userstock')
    buyer = models.ForeignKey(UserStocks, on_delete=models.CASCADE, related_name= 'buyer_userstock')
    amount=IntegerField('amount',default=0)
    quantity=IntegerField('quantity',default=0)
    soldAt=DateTimeField('dateTime',default=timezone.now, null = False, blank=False,help_text='Format : YYYY-MM-DDThh:mm')
    tag = models.CharField(max_length = 4, null = False, choices = TagChoices)

    def __str__(self):
      return 'StockPurchase'
"""

stocksapp/xplore/homeapp/forms.py
from django.forms import ModelForm
#from .models import StocksRecipts

#class StockBuyForm(ModelForm):
#    class Meta:
#        model = StocksRecipts
#        fields = '__all__'

stocksapp/xplore/homeapp/views.py
from django.shortcuts import render, redirect

#from .forms import StockBuyForm
from django.contrib.auth import get_user_model
from datetime import datetime
from homeapp.models import OrgStocks,PriceChange,Stocktype
from datetime import datetime
from pytezos import pytezos
#User = get_user_model()

# Create your views here.

def HomePage(request):
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return redirect('accounts/login.html')
        username = request.user.username
        stockid_in = request.POST.get('stocks')
        print(stockid_in)
        quantity = request.POST.get('fname')
        quantity=int(quantity)
        paymentAmount=request.POST.get("payment")
        stockt=Stocktype.objects.get(stockId=stockid_in)
        orData=OrgStocks.objects.filter(stockType=stockt)
        if len(orData)>0:
            orData=orData.first
            if(quantity<orData.stockAmount):
                price = PriceChange.objects.filter(is_linked=stockt)
                
                pyt =pytezos.using(key="edskRotpJzJHWX4zLsbuyfVnjeojJ3pmysGJEuXSvQWSvBqG1mS4x24TFjQhpiZQpKYNhzJT1DMfXbAE2YKVcuZE6fniECGeRB",shell="https://edonet.smartpy.io")
                contr=pyt.contract("KT1QNvidZC8e5U2UNnv72LUpDtoKfhzu1dge")
                orData.stockAmount-=quantity
                orData.save()
                contr.default(price=int(paymentAmount),quantity=int(quantity),stockType=stockid_in,to_from="Organization",username=username).inject()
                print("updaeyde")
            print("cant DO")
        else :
            print("cantDO")

    allorgStock=OrgStocks.objects.all()
    allorgData=[]
    for i in allorgStock:
        if i.stockAmount!=0:
            stoc=i.stockType
            pricecha=[]
            prices= PriceChange.objects.filter(is_linked=stoc)
            for itme in prices:
                pricecha.append(itme)
            newest_price=pricecha[-1].price
            lastPrice=1
            percentincrease=(newest_price-lastPrice)*100/lastPrice
            
            allorgData.append({
                'stock':stoc.stockName,
                'stockid':stoc.stockId,
                'price':newest_price,
                'percent_increase':percentincrease,
                'available':i.stockAmount
            })

    alloptions=Stocktype.objects.all()
    return render(request, 'homeapp/index.html',{'allorgData':allorgData,'tops':allorgData[0:3],'allOptions':alloptions})


    
    
    



                # quantity = stockbuyform.cleaned_data.get('fname')
                # stockType = stockbuyform.cleaned_data.get('stocks')
                # buyer = stockbuyform.cleaned_data(User.username)
                # seller = stockbuyform.cleaned_data("organization")
                # tag = stockbuyform.cleaned_data("Buy")
                # soldAt = stockbuyform.cleaned_data(datetime.now())
                # amount = stockbuyform.cleaned_data("1000")

                # orgstocktype = OrgStocks.objects.all().filter(stockType = stockType)
                # userstockincrement = UserStocks.objects.all().filter(username= User.username)
        #         if orgstocktype is not None:
        #             orgstocktype.stockNumber -= quantity
        #             userstockincrement.stockNumber += quantity
        #             return redirect('/')

        #         else:
        #             return redirect('/')


                

        #     return redirect('/')

        # else:
        #     stockbuyform = StockBuyForm()
    
        # context = {'stockbuyform' : "stockbuyform"}
        # return render(request, 'index.html', context)

stocksapp/xplore/homeapp/templates/homeapp/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

{% block head_block %}
<link rel="stylesheet" href="{% static "homeapp/index.css" %}">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

{% endblock %}

{% block body_block %}

<!-- Modal send the stock which is clicked -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
        <div>
          <!-- <p>Select Stock</p> -->
          <form action="{% url 'homeapp:homepage' %}", method="POST", id = "stockbuyform">
          <label for="stocks">Select stock:</label>
            {% csrf_token %}
           <select id="stocks" name="stocks", form="stockbuyform">
           
           {% for item in allOptions %}
            <option name='stocks' value={{ item.stockId }}>{{ item.stockName }}</option>

           {% endfor %}
            {% comment %} <option value="StockA">StockA</option>
            <option value="StockB">StockB</option>
            <option value="StockC">StockC</option>
            <option value="StockD">StockD</option>
            <option value="StockE">StockE</option>
            <option value="StockF">StockF</option>
            <option value="StockG">StockG</option> {% endcomment %}
          </select>
        </div>
          <label for="fname">Enter Quantity</label>
          <input type="text" id="fname" name="fname" type='number'><br><br>
          <label for="payment">Enter Payment Amount</label>
          <input type="text" id="payment" name="payment" type='number'><br><br>
          <button type="submit" value="submit" class="btn btn-primary container"   data-toggle="modal" data-target="#myModal"  style="background-color: #46c23a;"  >Buy</button>
        </form>

        <p>Trasation completion takes one mintue to complete</p>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<div class="container">
    <div class="row justify-content-between">
        <div class="col container" style="flex:2.5">
            <div  style="color: rgb(75, 75, 75);
            font-size: 17px;
            font-weight: 600;
          letter-spacing: 0px;
          color: rgb(86, 86, 86);margin-top: 10px;margin-bottom: 10px;">
                TOP GAINERS
            </div>
            {% for item in tops %}
            <div class="container card cardCustom">
                    <div class="row justify-content-between">
                        <div class="col">
                <div class="card-body">
                  <h5 class="card-title">{{ item.stock }}</h5>
                  <p class="card-text">{{ item.price }}<span style="color: #46c23a;">({{ item.percent_increase }}%)</span></p>
                  
                  <!-- <a href="#" class="btn btn-primary">Button</a> -->
                </div>
            </div>
            <div class="col">
                <div class="card-body">
                <img src="{% static "homeapp/graph.svg" %}" style="height: 60px;">
            </div>
            </div>
            <div class="col">
                <div class="card-body">
                    <p class="card-title" style="color: rgba(75, 75, 75, 0.897);">Stock Available {{ item.available }}</p>
                <a  class="btn btn-primary container"  data-toggle="modal" data-target="#myModal"  style="background-color: #46c23a;"  >Buy</a>
            </div>
            </div>

            </div>
              </div>

              {% endfor %}
              {% comment %} <div class="container card cardCustom">
                <div class="row justify-content-between">
                    <div class="col">
            <div class="card-body">
              <h5 class="card-title">Wheat</h5>
              <p class="card-text">68237.34<span style="color: #46c23a;">(+26.01%)</span></p>
              
              <!-- <a href="#" class="btn btn-primary">Button</a> -->
            </div>
        </div>
        <div class="col">
            <div class="card-body">
            <img src="{% static "homeapp/graph.svg" %}" style="height: 60px;">
        </div>
        </div>
        <div class="col">
            <div class="card-body">
                <p class="card-title" style="color: rgba(75, 75, 75, 0.897);">Stock Available 20.00</p>
            <a href="{% url 'homeapp:stockbuy' %}" class="btn btn-primary container"   data-toggle="modal" data-target="#myModal"  style="background-color: #46c23a;"  >Buy</a>
        </div>
        </div>

        </div>
          </div> {% endcomment %}
          {% comment %} <div class="container card cardCustom">
            <div class="row justify-content-between">
                <div class="col">
        <div class="card-body">
          <h5 class="card-title">Wheat</h5>
          <p class="card-text">68237.34<span style="color: #46c23a;">(+26.01%)</span></p>
          
          <!-- <a href="#" class="btn btn-primary">Button</a> -->
        </div>
    </div>
    <div class="col">
        <div class="card-body">
        <img src="{% static "homeapp/graph.svg" %}" style="height: 60px;">
    </div>
    </div>
    <div class="col">
        <div class="card-body">
            <p class="card-title" style="color: rgba(75, 75, 75, 0.897);">Stock Available 20.00</p>
        <a href="{% url 'homeapp:stockbuy' %}" class="btn btn-primary container"   data-toggle="modal" data-target="#myModal"  style="background-color: #46c23a;"  >Buy</a>
    </div>
    </div>

    </div>
      </div> {% endcomment %}

      <div  style="color: rgb(75, 75, 75);
            font-size: 17px;
            font-weight: 600;
          letter-spacing: 0px;
          color: rgb(86, 86, 86);margin-top: 30px;margin-bottom: 20px;">
                All Organization STOCKS
            </div>

      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Crop</th>
            <th scope="col">Market Price</th>
            <th scope="col">Stocks Available</th>
            <th scope="col"></th>
            <th scope="col">Buy stocks</th>
          </tr>
        </thead>
        <tbody>
          {% for item in allorgData %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ item.stock }}</td>
            <td>{{ item.price }}<span style="color: #46c23a;">( {{ item.percent_increase }} %)</span></td>
            <td>{{ item.available }}</td>
            <td><img src="{% static "homeapp/graph.svg" %}" style="height: 20px;"></td>
            <td><a class="container"   data-toggle="modal" data-target="#myModal"  style="color: #46c23a;text-align: left;">BUY</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>


        </div>
        <div class="col">
            <div class="card cardCustom">
                <div class="card-body">
                  <!-- <h5 class="card-title" style="text-align: center;">History</h5> -->
                  <p class="card-text" style="text-align: center;">Season Ends in 10 months</p>
                </div>
              </div>
            <div class="card cardCustom">
                <img class="card-img-top" src="https://img.freepik.com/free-vector/online-shopping-mobile-phone-ecommerce-market-flat-illustration-with-small-people_135170-27.jpg?size=626&ext=jpg" alt="Card image cap">
                <div class="card-body">
                  <!-- <h5 class="card-title" style="text-align: center;">History</h5> -->
                  <p class="card-text" style="text-align: center;">Buy new stock before season ends or Sell stock.</p>
                  <a  class="btn btn-primary container"  data-toggle="modal" data-target="#myModal" style="background-color: #46c23a;" >Buy / Sell</a>
                </div>
              </div>
              <div class="card cardCustom">
                <img class="card-img-top" src="https://media.istockphoto.com/vectors/open-banking-platform-concept-vector-illustration-vector-id1169397219?k=6&m=1169397219&s=612x612&w=0&h=gTpdNTwdezBUed4TuYYfGB8ZruzPsiIwjEdiNmhEG-U=" alt="Card image cap">
                <div class="card-body">
                  <!-- <h5 class="card-title" style="text-align: center;">History</h5> -->
                  <p class="card-text" style="text-align: center;">Check your past transactions</p>
                  <a href="{% url 'history:buying_history' %}" class="btn btn-primary container" style="background-color: #46c23a;"  >Transactions History</a>
                  {% comment %} <a href="{% url 'history:selling_history' %}" class="btn btn-primary container" style="background-color: #46c23a;"  >Selling History</a> {% endcomment %}
                </div>
              </div>
              <!-- <div class="card cardCustom">
                <div class="card-body">
                  <p class="card-text" style="text-align: center;">New to Stocks?</p>
                  <a href="#" class="btn btn-primary container" style="background-color: #46c23a;"  >Buy</a>
                </div>
              </div> -->
        </div>
      </div>
</div>
{% endblock %}